version: '3'

services:
  ble-triangulation:
    build: ./triangulation_service
    container_name: ble-triangulation
    restart: unless-stopped
    volumes:
      - ./triangulation_service/proxies.yaml:/app/proxies.yaml
    environment:
      - MQTT_HOST=${MQTT_HOST:-localhost}
      - MQTT_PORT=${MQTT_PORT:-1883}
      - MQTT_USERNAME=${MQTT_USERNAME:-}
      - MQTT_PASSWORD=${MQTT_PASSWORD:-}