# ESPHome Secrets Example File
# Copy this file to 'secrets.yaml' in your ESPHome configuration directory
# and fill in your actual values

# WiFi Configuration
wifi_ssid: "YourWiFiSSID"
wifi_password: "YourWiFiPassword"

# Fallback AP Configuration
fallback_ap_password: "FallbackPassword123"

# OTA Update Password
ota_password: "OTAPassword123"

# MQTT Configuration
mqtt_broker: "192.168.1.100"  # Your MQTT broker IP or hostname
mqtt_username: "mqtt_user"
mqtt_password: "mqtt_password"

# Home Assistant API encryption key (required for bluetooth-proxy packages)
# Generate with: openssl rand -base64 32
api_encryption_key: "53N2oko1Me6XgA7ZyHV13I7e9LmCKbNPUpARhopwo+8="