# Example Home Assistant configuration.yaml entries

# MQTT Connection (if not already configured)
mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: true
  discovery_prefix: homeassistant

# Map card configuration for your dashboard
type: map
entities:
  - entity: device_tracker.beacon_c7_9b_6a_32_bb_0e
title: BLE Beacon Location
hours_to_show: 24
default_zoom: 15

# Example automation to notify when a beacon enters or leaves a zone
automation:
  - alias: "Notify when Jayden's Backpack arrives home"
    trigger:
      - platform: state
        entity_id: device_tracker.beacon_c7_9b_6a_32_bb_0e
        to: "home"
    action:
      - service: notify.mobile_app
        data:
          message: "Jayden's backpack has arrived home"
          title: "Backpack Tracking"

  - alias: "Notify when Jayden's Backpack leaves home"
    trigger:
      - platform: state
        entity_id: device_tracker.beacon_c7_9b_6a_32_bb_0e
        from: "home"
    action:
      - service: notify.mobile_app
        data:
          message: "Jayden's backpack has left home"
          title: "Backpack Tracking"